JRELEASER_GITHUB_TOKEN = "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"
JRELEASER_MAVENCENTRAL_USERNAME = "xPpvapVZ"
JRELEASER_MAVENCENTRAL_PASSWORD = "STxDr8MMsGRRSyp0SQ6ADhok7Lp8YiqsI/5tpBGVn2Eu"
JRELEASER_GPG_PASSPHRASE = "Quetefollen69veces+"

JRELEASER_GPG_PUBLIC_KEY="""-----BEGIN PGP PUBLIC KEY BLOCK-----

mQGNBGc/F04BDADAiszBN8TO+UTnY2s5C00Y9nUHUBb/lzudyWzBGZXZV9nvwZ2d
dNlUyqwf5miFdJjHNzrnm1uNi1ZeARvoCQ+mLLlBgSEW+KyYkqZdNcmg9vzRzySr
UxaxLSl8YVwX4Ib2EvIcpGpbz1NjAT5ecyI+nNopHl7saAsJ7yupJtN+3bUFdPaM
MGlZYqgaOP5D4cEF8+CayHpZfpplcAqzCAgzZwOZdQkjLHtcUxo1IvBUNXXAvHXE
Fk0FgTWPoNxkMmsjgVAJwZBd5XY4rTdj4u/xYHamcyUOInX6LvUjKoi88KKQc9rE
Ib2PkVvWShZCbNJzG5YnTCeIr3gUvEu7lMQAyDGrGlNza/vmJQ4VZYpMCPFyzj1K
3PtliT3tzDk0H2lj2UaQ3ZLJZzv9gUOKRPwnoR/8Cu7n5NOkyXHZWiQPQaKBM27t
hhjg66dMUta61f6VYNbHs3sXUB0M+7k1mtiPs/7XyXg8TBr5xs8T0hIMfkmpSTn/
4hPzdtdxaLirja8AEQEAAbRWQW50b25pbyBQZXJleiBEaWVwcGEgKFRvIHJlbGVh
c2UgTW9uZ29jay9mbGFpbmdvY2sgYXJ0ZWZhY3RzKSA8YXBlcmV6ZGllcHBhQGdt
YWlsLmNvbT6JAdEEEwEIADsWIQQohGcwOa3+A4W64GTkIwjYfXUJAwUCZz8XTgIb
AwULCQgHAgIiAgYVCgkICwIEFgIDAQIeBwIXgAAKCRDkIwjYfXUJA+EADACP4zcv
PT8tIUCH5HYjLuV8cpzbg7S8uun0ipygczHscD5MI6f0WqS206SRPX0Vh7nCBY0w
eVjuvXt64J0mzfcwkaI7sOSVKRyqORl5Bj3Okej5MjCk4tzSV42aAc9cHveNsX11
2ntC4zWCmWENOgr4dtwMD9Xfkd166DW2TAgikG9MIVeacVNyxS7GyxPcjwFDN6/f
PUbCCb3oVen1xP6b+rru/fNaevFf3S33kFnxmyTdIORBpm3AE4k1MKFFmpsVDYV3
zXc+xyLBjSUYy8CC8tl9v/9qT/bMIQg2ZacoGfGY1fBrv54tVT5Qx2rMYEJJ62tE
zb8VtaLCcb7HVn2vA0iYyWrrVwFEbGELecCDHtSrWnt2qz0D1qHSwzb7sd5LqP41
hyHRu1q0/S6Z8FjAbM3lg6ep/pzuJ8Otbnom+/BeLxwaJ1G4K994DumcuAQv5XT7
l/XoPKyI1FZO97Dfr44HIKag786XW7IjRWfBGgda1eOfjiKLMGxcdrTprLy5AY0E
Zz8XTgEMAOWElqpQBRnInOmaiL1k7ff3pjxsX5aJf1ETJvw5V6NckXvugamziHKY
F3X/VzqVNpV2iJv3WZRXJjCFb1x4vCeNFIFJetAPqZk435t/KuQE08Gvz3OfBdFD
Q5kJHKb1FeksXojVqQvcE7trVirXhNI6ByBvgVWmmY4oS4cLOWF25gIFT5yNx7hH
AC7vDmF9Ik9jgaajkcuAQpJvwzn5TGgpuO8NvEdEuZPwUdFnLxloAODaIl1tBgVH
SgVYCafSlYogdmO/ghIxt9AOblmFHnNsNSmMrswieqxN4RS5LXarEKJrWYKitnOY
EDv4JT1mSZhMqmt2zdScUpfQRZdUOctcJB6x1jVstMkmbI87lgAI7dYexobpY926
2LkbFyQrtDVu6785C12BGqr/0yETWpd2PoUSv29AGlNL6bz1isQ3XiO46qp8UTMj
9Ob+9IZD4J5/8TyHsoYuTulmTP2X8+Xgr69iegKMgJ7ILv74m8I5fT5J3fJrprVL
FPeiSfaIbQARAQABiQG2BBgBCAAgFiEEKIRnMDmt/gOFuuBk5CMI2H11CQMFAmc/
F04CGwwACgkQ5CMI2H11CQOV2Av7B6vh4G1rS9//g5jy4WJtB6FtS0Sf9/dLFg7O
DzkCbej1DR+FZzzOq1Oizr1cVEELTAFaF3ZrGBFiWF+ZTRPQmvgQ/HRTBMod0TMb
U2SzY3VNAg69N5UmpSmtQ1hG+MaM32WqhZkuFxl5kT4mhoE8o90RVautfSsZAFng
OANaH0Ncgf+AuUbiIh/sWuhTc71BVKLiZmLFurbNvZRcTHugLuzgVux5cETOwLk0
SxrxFtQTTexgG9OQNxFRTTXGq9lHOdTP2J6nNeG3S/sTexKjmuK7lMcIhmxDc77A
GPQnh2Q0YK1TaX8EReMhIVdTWwtxfq/TjRgT4piBCI03GAvZilhyM5CY2KgvsKq8
hA5whMJVQWqVZ5H+obIf5UpeeQFGblMyHnHd2sh0AkQtF+Tlwmr+kAxp+XUQrl/9
6KMoXyNYXUaryakzsGGNdTiDUEK/7YyjtfMiQ2+vfTPGtSlgHSWbjepTBTQ/MBk7
2P687dlae0sg6MuuBDmOX+5coAGI
=EFWj
-----END PGP PUBLIC KEY BLOCK-----"""

JRELEASER_GPG_SECRET_KEY="""-----BEGIN PGP PRIVATE KEY BLOCK-----

lQWGBGc/F04BDADAiszBN8TO+UTnY2s5C00Y9nUHUBb/lzudyWzBGZXZV9nvwZ2d
dNlUyqwf5miFdJjHNzrnm1uNi1ZeARvoCQ+mLLlBgSEW+KyYkqZdNcmg9vzRzySr
UxaxLSl8YVwX4Ib2EvIcpGpbz1NjAT5ecyI+nNopHl7saAsJ7yupJtN+3bUFdPaM
MGlZYqgaOP5D4cEF8+CayHpZfpplcAqzCAgzZwOZdQkjLHtcUxo1IvBUNXXAvHXE
Fk0FgTWPoNxkMmsjgVAJwZBd5XY4rTdj4u/xYHamcyUOInX6LvUjKoi88KKQc9rE
Ib2PkVvWShZCbNJzG5YnTCeIr3gUvEu7lMQAyDGrGlNza/vmJQ4VZYpMCPFyzj1K
3PtliT3tzDk0H2lj2UaQ3ZLJZzv9gUOKRPwnoR/8Cu7n5NOkyXHZWiQPQaKBM27t
hhjg66dMUta61f6VYNbHs3sXUB0M+7k1mtiPs/7XyXg8TBr5xs8T0hIMfkmpSTn/
4hPzdtdxaLirja8AEQEAAf4HAwL3wF40akH/lPQIMy0O5BfdZKYecEMIPP75Utpu
3LI2gFLS+P8oWlozNw044MIiphnJZ9Fz5XUI2wB7UGgj0ZZA/WquMqiX1OZR6YB9
jEXNH7z5s/eBoQl6nee1lqS1JxDzGhoU5PTlscSsVBo9sD4BKsekjBs7gKfVCW8f
oYc6e4RQz5MuQ+7C75WdETnzfEHqPR4N6VIhJqXd6fu2DipLAEWvETMoxJ8lMNxp
pIA+2p4azgM97J3DQYpdatEnsE267K0G4LDVnuYzsoqyqOqcppKVqW25AcdkAkwL
KaTPmc1adHPtajfSXXr11NvRymESClmtRIJSb/X2OsKYBO5wCc676AuGRNQ9zkhf
hcONLyKBSlceyhkF7RDxBhDwQw+WJvSkch3Bd4PWKjtnwsPc9C2fSQapscPnFx3m
eKSH47UjMonVmRBvoNFJ3gpSe97+1GzXoVYRqZnUaPdZx5EXPcsxLVO2rUBkp9tj
8ytcqaidgqh9pbnkqPLBQbrk+olxCHu1m72bA4DcuKLcRa3yaXQnN8wSvUi0WeAW
Gc1X4wU8ED/DlcE6QhZgub6nRLzlh2nciVsaR3JlAE/bHWxTGBaqGpxc+Pem0Oty
TNnWmZmqnOnv/j4AIzMz9bEW749Vo5h3TjQbMgYt/5M8onTP/qvi9kysygApAC13
WiVLsEfjjeyKYbUUCj7Ilf3hJvXx9Hk5FT0T12NnCeqT39HCHUYqDfOke9f0Ym6J
RD9yXbF9CQd5+9BGH6HwTSolKtZy472Tw3EfGXYeU/WeLS+QuLJQZYBBmOkw4mb0
1HgQXOpbedSZWgs+/9O85jUbXAAiP1lYuapa/DgeMJA+68BdR04ZYXYZvgLZjCgb
dblS7PUL4BDrX+2sDpasfl2uRaJN/rZVEv7JZ/vXQdQPZdBvIDKgJYZoJq1erNVP
2GVONMLNgJoNRYkg1NacVaL3xPpFgag2qh/mio8CnNT/PzfieJklnOyFNxooQIrB
kUR2n/Xv5kMBZBqpj3UXxJAyCKUDE2Nf3J/0rRaf7D1wRLwvqVUcWaOKHLbMfIe0
YGtGGR/1fPbGCM1+C3dryqdX025QOQDBcYtw3IkBjBMNsMjNeheHmBT1BVktbX1E
3AGhIJO++QkNC1ZvYu7w81utRjKshkVJD0enonVH3eKNo4ufR65cMwfjWw2ad0LW
nYOcM+QNBASaoiJ6QDDb2FMLse2p70Y+1DAyWZYhulIRAsOzyvW9zMetgpebknNT
KrFRKzPl5INxZgLMkCsE2wHV0UzU69q3rX12DDjguytz4Qv3ZWFF0pZH9+P6forC
GV58YdYk8DqAsojcE3vqegVT9EkLgMliAbRWQW50b25pbyBQZXJleiBEaWVwcGEg
KFRvIHJlbGVhc2UgTW9uZ29jay9mbGFpbmdvY2sgYXJ0ZWZhY3RzKSA8YXBlcmV6
ZGllcHBhQGdtYWlsLmNvbT6JAdEEEwEIADsWIQQohGcwOa3+A4W64GTkIwjYfXUJ
AwUCZz8XTgIbAwULCQgHAgIiAgYVCgkICwIEFgIDAQIeBwIXgAAKCRDkIwjYfXUJ
A+EADACP4zcvPT8tIUCH5HYjLuV8cpzbg7S8uun0ipygczHscD5MI6f0WqS206SR
PX0Vh7nCBY0weVjuvXt64J0mzfcwkaI7sOSVKRyqORl5Bj3Okej5MjCk4tzSV42a
Ac9cHveNsX112ntC4zWCmWENOgr4dtwMD9Xfkd166DW2TAgikG9MIVeacVNyxS7G
yxPcjwFDN6/fPUbCCb3oVen1xP6b+rru/fNaevFf3S33kFnxmyTdIORBpm3AE4k1
MKFFmpsVDYV3zXc+xyLBjSUYy8CC8tl9v/9qT/bMIQg2ZacoGfGY1fBrv54tVT5Q
x2rMYEJJ62tEzb8VtaLCcb7HVn2vA0iYyWrrVwFEbGELecCDHtSrWnt2qz0D1qHS
wzb7sd5LqP41hyHRu1q0/S6Z8FjAbM3lg6ep/pzuJ8Otbnom+/BeLxwaJ1G4K994
DumcuAQv5XT7l/XoPKyI1FZO97Dfr44HIKag786XW7IjRWfBGgda1eOfjiKLMGxc
drTprLydBYYEZz8XTgEMAOWElqpQBRnInOmaiL1k7ff3pjxsX5aJf1ETJvw5V6Nc
kXvugamziHKYF3X/VzqVNpV2iJv3WZRXJjCFb1x4vCeNFIFJetAPqZk435t/KuQE
08Gvz3OfBdFDQ5kJHKb1FeksXojVqQvcE7trVirXhNI6ByBvgVWmmY4oS4cLOWF2
5gIFT5yNx7hHAC7vDmF9Ik9jgaajkcuAQpJvwzn5TGgpuO8NvEdEuZPwUdFnLxlo
AODaIl1tBgVHSgVYCafSlYogdmO/ghIxt9AOblmFHnNsNSmMrswieqxN4RS5LXar
EKJrWYKitnOYEDv4JT1mSZhMqmt2zdScUpfQRZdUOctcJB6x1jVstMkmbI87lgAI
7dYexobpY9262LkbFyQrtDVu6785C12BGqr/0yETWpd2PoUSv29AGlNL6bz1isQ3
XiO46qp8UTMj9Ob+9IZD4J5/8TyHsoYuTulmTP2X8+Xgr69iegKMgJ7ILv74m8I5
fT5J3fJrprVLFPeiSfaIbQARAQAB/gcDAgNsDLX2hYfs9KLQPMJe0LNmzpiQOFwt
FVgHH8cDy7ArOOK6lw7YZcxFXBBbvXGQ5KMru1NJnGvsLsV6SALbOAtd76FPO/kD
tZAKIl+dEEU2Jxq8dQbMQY8wFfpYsIMmNBNKcZ4s7lGuK2oxEy4AID08E0gTOizi
KjX6XZjWVwN+HK8W8xzRBcS7fozfOLPbKDWWjhAo7pwNs7uS7+B+guDgKhuAS0N6
38PmzTWiD0cIfx3Ps4DtJ2HTr3cT6Yufc6bvOs7jUiCsRsJpSrrMFtdEt5ztZhmO
A3hJRSy+Gz81EXcIA3rX1SSX0RGTAjBRqqsgjvgM6UjEPBZznmC3ipe5fg3BVi+H
dSctn2hBm0Q/AwttTiAH+nD+uEspS21q6IsbeVVuCsaMkaYP1YQQIn6qUWc3WojU
faenW7LqoJLjaAze2XUM6X72aNR4KFiuzZ34WBf0SIbrpn+iN3ZtsnULWRl7Ccyk
mL3L3Wp/AXyX8LG4BpdNYE2sSYSqaFq+Ksl9zIr5zVHq3hBR4myBxXbFV8K1rdID
wmWXYACIE7u6owE0APU9J31ZhLz6aVXxLnhsgyzhBrkcQr51rYxsZz5/9w4JzUVo
To3150A3gni3R57/cI2US/j4dzLTF6Wx0894MhGe6DHv6+1sUP43UYAxWF5hrTRH
zvkHzBvFB29qKpJZPrymcrkKKUAxxiCIyo0CflK4wY3hN3Bz8WBRJG3XHriBvCqx
6RhK9UzOUUZB2sBx6K7fm7VjOA6UPXkfrVs8lLYVpLPNtG217r01YdoQJHrHJntI
2Cj9rm8lEHFCkX/krreumnLv7fzam/p8TK4wlX+4cbPwMYTROs3lQWF0otYmFHCe
uFKaIhGAmFDUZp3HorKb7xrkWn7IngedCGq3HZjVnJy1MrHXUDrlwvHsug8iszqD
9V4VK7rLsnolzQjjA9rBtm1lONJRs982wS2hUrZx4C9QTdahZC8T7YMI1GtudVA6
L2T/g0tyL4fsQ/3t14w49z0TXg7e94FZTfFoUuKowpoAJ7Acbm+iu30XDT0Ezhbe
yuc3et5SDek2/H8adIl5mLn31FgN+5SR83QsDtNESc7TBUnHtFnhczFDT5IiKmLl
AJvi0PAHu05XhmrH+Lo/5ImDagiXKuQh5pBl8Byy6s6dgpfbgIFm3iHNjf2xbYBC
nOsztG8m6SG8IATFVZXaNBoKfge5O7V/iK5ivQavhftHGkuBx4+ihZZJw2bQkHn8
JczM5GVkTQmjNuQKeObBaG4CuiX9NN+785ygEAb0IO9X3bQv92iqgWywfi/q1qnJ
k2ktepiJoHo/W4DrcPbtNUqy0l2k9BRoa0rW0Dt8iQG2BBgBCAAgFiEEKIRnMDmt
/gOFuuBk5CMI2H11CQMFAmc/F04CGwwACgkQ5CMI2H11CQOV2Av7B6vh4G1rS9//
g5jy4WJtB6FtS0Sf9/dLFg7ODzkCbej1DR+FZzzOq1Oizr1cVEELTAFaF3ZrGBFi
WF+ZTRPQmvgQ/HRTBMod0TMbU2SzY3VNAg69N5UmpSmtQ1hG+MaM32WqhZkuFxl5
kT4mhoE8o90RVautfSsZAFngOANaH0Ncgf+AuUbiIh/sWuhTc71BVKLiZmLFurbN
vZRcTHugLuzgVux5cETOwLk0SxrxFtQTTexgG9OQNxFRTTXGq9lHOdTP2J6nNeG3
S/sTexKjmuK7lMcIhmxDc77AGPQnh2Q0YK1TaX8EReMhIVdTWwtxfq/TjRgT4piB
CI03GAvZilhyM5CY2KgvsKq8hA5whMJVQWqVZ5H+obIf5UpeeQFGblMyHnHd2sh0
AkQtF+Tlwmr+kAxp+XUQrl/96KMoXyNYXUaryakzsGGNdTiDUEK/7YyjtfMiQ2+v
fTPGtSlgHSWbjepTBTQ/MBk72P687dlae0sg6MuuBDmOX+5coAGI
=vO5L
-----END PGP PRIVATE KEY BLOCK-----"""
