flamingock:
  stages:
    - name: stage2
      parallel: true
      depends: stage1
      code-packages:
        - io.flamingock.examples.community.changes
      file-directories:
        - flamingock/stage1
  transactionEnabled: true
