flamingock:
  stages:
    - name: stage1
      code-packages:
        - io.flamingock.examples.community.changes
      file-directories:
        - flamingock/stage1
  transactionEnabled: true
  templates-imported:
    - com.company.templates.MongoModule
