name: Build examples
on:
  workflow_dispatch:
    branches:
      - master
jobs:
  print-message:
    runs-on: ubuntu-latest
    steps:
      - name: Print message
        run: echo "Hello world"

  run-examples-test:
    needs: [ print-message ]
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout flamingock-examples repository
        uses: actions/checkout@v3
        with:
          repository: mongock/flamingock-examples  # Checkout flamingock-examples repo
          ref: master  # Use the master branch of flamingock-examples
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run Gradle build on flamingock-examples
        run: ./gradlew clean build


#      - name: Synchronizing develop branch
#        run: |
#          git pull origin
#          git checkout develop
#          git merge -X theirs master --allow-unrelated-histories
#          git push origin develop
