name: Build examples
on:
  workflow_dispatch:
    branches:
      - master
jobs:
  run-examples-test:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout flamingock-examples repository
        uses: actions/checkout@v3
        with:
          repository: mongock/flamingock-examples  # Checkout flamingock-examples repo
          ref: master  # Use the master branch of flamingock-examples

      - name: Run Gradle build on flamingock-examples
        run: ./gradlew clean build


#      - name: Synchronizing develop branch
#        run: |
#          git pull origin
#          git checkout develop
#          git merge -X theirs master --allow-unrelated-histories
#          git push origin develop
