name: Build examples
on:
  workflow_dispatch:
    branches:
      - master
jobs:
  run-examples-test:
    continue-on-error: true
    uses: mongock/flamingock-examples/.github/workflows/build_dispatched.yml@master


#      - name: Synchronizing develop branch
#        run: |
#          git pull origin
#          git checkout develop
#          git merge -X theirs master --allow-unrelated-histories
#          git push origin develop
