name: Manual Trigger with Inputs

on:
  workflow_dispatch:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Display Inputs
        run: |
          echo "Pimpan"
          echo "Takekua"
