name: Release
on:
  workflow_dispatch:
    branches:
      - master
jobs:
  flamingock-core:
    name: Release flamingock-core module to Central Portal
    uses: ./.github/workflows/module-release.yml
    with:
      module: flamingock-core
    secrets:
      FLAMINGOCK_JRELEASER_GITHUB_TOKEN: ${{ secrets.FLAMINGOCK_JRELEASER_GITHUB_TOKEN }}
      FLAMINGOCK_JRELEASER_MAVENCENTRAL_USERNAME: ${{ secrets.FLAMINGOCK_JRELEASER_MAVENCENTRAL_USERNAME }}
      FLAMINGOCK_JRELEASER_MAVENCENTRAL_PASSWORD: ${{ secrets.FLAMINGOCK_JRELEASER_MAVENCENTRAL_PASSWORD }}
      FLAMINGOCK_JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.FLAMINGOCK_JRELEASER_GPG_PUBLIC_KEY }}
      FLAMINGOCK_JRELEASER_GPG_SECRET_KEY: ${{ secrets.FLAMINGOCK_JRELEASER_GPG_SECRET_KEY }}
      FLAMINGOCK_JRELEASER_GPG_PASSPHRASE: ${{ secrets.FLAMINGOCK_JRELEASER_GPG_PASSPHRASE }}

  flamingock-core-api:
    name: Release flamingock-core-api module to Central Portal
    uses: ./.github/workflows/module-release.yml
    with:
      module: flamingock-core-api
    secrets:
      FLAMINGOCK_JRELEASER_GITHUB_TOKEN: ${{ secrets.FLAMINGOCK_JRELEASER_GITHUB_TOKEN }}
      FLAMINGOCK_JRELEASER_MAVENCENTRAL_USERNAME: ${{ secrets.FLAMINGOCK_JRELEASER_MAVENCENTRAL_USERNAME }}
      FLAMINGOCK_JRELEASER_MAVENCENTRAL_PASSWORD: ${{ secrets.FLAMINGOCK_JRELEASER_MAVENCENTRAL_PASSWORD }}
      FLAMINGOCK_JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.FLAMINGOCK_JRELEASER_GPG_PUBLIC_KEY }}
      FLAMINGOCK_JRELEASER_GPG_SECRET_KEY: ${{ secrets.FLAMINGOCK_JRELEASER_GPG_SECRET_KEY }}
      FLAMINGOCK_JRELEASER_GPG_PASSPHRASE: ${{ secrets.FLAMINGOCK_JRELEASER_GPG_PASSPHRASE }}

  flamingock-core-template:
    uses: ./.github/workflows/module-release.yml
    with:
      module: flamingock-core-template
    secrets:
      FLAMINGOCK_JRELEASER_GITHUB_TOKEN: ${{ secrets.FLAMINGOCK_JRELEASER_GITHUB_TOKEN }}
      FLAMINGOCK_JRELEASER_MAVENCENTRAL_USERNAME: ${{ secrets.FLAMINGOCK_JRELEASER_MAVENCENTRAL_USERNAME }}
      FLAMINGOCK_JRELEASER_MAVENCENTRAL_PASSWORD: ${{ secrets.FLAMINGOCK_JRELEASER_MAVENCENTRAL_PASSWORD }}
      FLAMINGOCK_JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.FLAMINGOCK_JRELEASER_GPG_PUBLIC_KEY }}
      FLAMINGOCK_JRELEASER_GPG_SECRET_KEY: ${{ secrets.FLAMINGOCK_JRELEASER_GPG_SECRET_KEY }}
      FLAMINGOCK_JRELEASER_GPG_PASSPHRASE: ${{ secrets.FLAMINGOCK_JRELEASER_GPG_PASSPHRASE }}

      #
#  github-release:
#    needs: [flamingock-core, flamingock-core-api, flamingock-core-template]
#    uses: ./.github/workflows/github-release.yml




      #  "flamingock-core-template",
      #  "flamingock-springboot-v2-runner",
      #  "flamingock-springboot-v3-runner",
      #  "utils"
      #  "driver-common",
      #  "couchbase-driver",
      #  "couchbase-springboot-v2-driver",
      #  "dynamodb-driver",
      #  "mongodb-facade",
      #  "mongodb-springdata-v2-driver",
      #  "mongodb-springdata-v3-driver",
      #  "mongodb-springdata-v4-driver",
      #  "mongodb-sync-v4-driver",
      #  "mongodb-v3-driver"
      #  "sql-template",
      #  "sql-springboot-template"
      #  "sql-cloud-transactioner"



#  release-output:
#    name: JReleaser release output
#    if: always()
#    uses: actions/upload-artifact@v4
#    with:
#      name: jreleaser-release
#      path: |
#        build/jreleaser/output.properties
#        build/jreleaser/trace.log

#      - name: Synchronizing develop branch
#        run: |
#          git pull origin
#          git checkout develop
#          git merge -X theirs master --allow-unrelated-histories
#          git push origin develop
